Refactor: Prisma Client API reference
prisma/prisma2-docs pull request #1014
Opened 2020-11-13 12:30 UTC by mhwelander

2021-01-26 11:36 UTC, nikolasburk requested changes
Spectacular work Martina, this is soooo good!

I've left a couple of comments, mostly wrt to consistency and formatting. Sorry that I'm so pedantic with that kind of stuff at times 🙈

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +0
```suggestion
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +`select` defines which fields are included in the selection set that Prisma Client returns. See: [Select fields and include relations](../../../concepts/components/prisma-client/select-fields) <span
```suggestion
`select` defines which fields are included in the object that Prisma Client returns. See: [Select fields and include relations](../../../concepts/components/prisma-client/select-fields) <span class="concept"></span>.
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +#### Examples
no `CmdResult`s here? 😢

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +```ts
I noticed that you're not using the `index.d.ts` file annotation here. We should probably be consistent with this across the entire page.

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +#### Examples
is there a reason why the output in the examples is shown by default but for others it's not?

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +;[
```suggestion
[
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +;[
```suggestion
[
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +;[
```suggestion
[
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +|     create: { bio: 'Hello World' },
Seems like this needs an extra space

```suggestion
|      create: { bio: 'Hello World' },
```

![image](https://user-images.githubusercontent.com/4058327/105838472-69ee6700-5fd0-11eb-8612-0261be7038fa.png)

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +|     create: { email: 'alice@prisma.io' },
```suggestion
|      create: { email: 'alice@prisma.io' },
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +|     create: { title: 'Hello World' },
```suggestion
|      create: { title: 'Hello World' },
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +|     create: [{ title: 'This is my first post' }, { title: 'Here comes a second post' }],
```suggestion
|      create: [{ 
        title: 'This is my first post' 
      }, { 
        title: 'Here comes a second post' 
      }],
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +|     create: { bio: 'Hello World' },
```suggestion
|      create: { bio: 'Hello World' },
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +```
not needed any more as of 2.15 :)

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +```ts
seems like the entire code block is falsely indented

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +  const result = await prisma.user.findMany({
seems like the entire code block is falsely indented

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +The `$disconnect()` method closes the database connections that were established when `$connect` was called and stops the process that was running Prisma's query engine. See [Connection management fo
IMO closing the link a bit earlier makes this look cleaner/less noisy

```suggestion
The `$disconnect()` method closes the database connections that were established when `$connect` was called and stops the process that was running Prisma's query engine. See [Connection management](../../..//concepts/components/prisma-client/connection-management) for an overview of `$connect()` and `$disconnect()`.
```

![image](https://user-images.githubusercontent.com/4058327/105839181-64dde780-5fd1-11eb-83d1-cc5cb25f2127.png)

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +- `*$disconnect()` returns a `Promise`, so you should call it inside an `async` function with the `await` keyword.
```suggestion
- `$disconnect()` returns a `Promise`, so you should call it inside an `async` function with the `await` keyword.
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +The `$connect()` method establishes a physical connection to the database via Prisma's query engine. See [Connection management for an overview of `$connect()` and `$disconnect()`](../../..//concepts
```suggestion
The `$connect()` method establishes a physical connection to the database via Prisma's query engine. See [Connection management](../../..//concepts/components/prisma-client/connection-management) for an overview of `$connect()` and `$disconnect()`.
```

2021-01-26 11:36 UTC, nikolasburk commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +- `*$connect()` returns a `Promise`, so you should call it inside an `async` function with the `await` keyword.
```suggestion
- `$connect()` returns a `Promise`, so you should call it inside an `async` function with the `await` keyword.
```

2021-01-26 11:36 UTC, nikolasburk commented on content/200-concepts/100-components/02-prisma-client/035-select-fields.mdx
> +title: 'Select fields'
I think this page should highlight a couple of more things:

- examples for `include`
- examples for nested combos of `select` and `include`

2021-01-26 11:36 UTC, nikolasburk commented on content/200-concepts/100-components/02-prisma-client/035-select-fields.mdx
> +- **All** scalar fields defined in the Prisma schema
```suggestion
- **All** scalar fields defined in the Prisma schema (including enums)
```

2021-01-26 11:36 UTC, nikolasburk commented on content/200-concepts/100-components/02-prisma-client/050-filtering-and-sorting.mdx
> +Follow [issue #1 on GitHub](https://github.com/prisma/prisma-client-js/issues/1).
seems like this was introduced with `groupBy`? https://github.com/prisma/prisma-client-js/issues/1

2021-01-26 12:06 UTC, mhwelander commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +- You must re-generate the Prisma Client each time you add or rename a datasource. Datasource names are included in the generated client.
Good point - I think this is one of the few instances of datasource as opposed to data source. I'll pick data source and update the style guide.

2021-02-02 10:45 UTC, mhwelander commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +| `error` | Errors.                                              |
https://github.com/prisma/docs/issues/1245

2021-02-02 11:49 UTC, mhwelander commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +<CmdResult>
It's just me doing the ones I can for now - have created a clean-up GH issue to go through and make sure all examples have CLI output.

2021-02-03 14:22 UTC, merged