Added emacs note to editor setup
prisma/prisma2-docs pull request #1506
Opened 2021-03-30 07:16 UTC by molebox

Fixes #1505

2021-03-30 11:32 UTC, janpio requested changes
This is not an official editor supported by us, so we should probably mention that this is a community thing that might work or not. This also means, the other editors do not have the same features. It should definitely not be listed on the same level as VSCode which we developer and spend a lot of effort on.

2021-03-30 11:43 UTC, molebox commented
> This is great.
> 
> But: This is not an official editor supported by us, so we should probably mention that this is a community thing that might work or not. This also means, the other editors do not have the same features. It should definitely not be listed on the same level as VSCode which we developer and spend a lot of effort on.

You know what, i was actually going to ask exactly this question. I can add a community supported section and list this there

2021-03-30 12:15 UTC, janpio commented on content/200-concepts/300-more/100-editor-setup.mdx
> +
Maybe a disclaimer here that these are not offered by us, might not have the same or complete feature set and so on.

2021-03-30 12:17 UTC, pimeys commented
We btw. have language server working on Emacs, thanks to @pantharshit00. So, it seems Emacs is now BETTER than VSCode :)

2021-04-01 09:01 UTC, nikolasburk commented
If we start adding community extensions here, we also might want to include the one for Jetbrains IDEs: https://plugins.jetbrains.com/plugin/14240-prisma

2021-04-06 07:45 UTC, mhwelander commented on content/200-concepts/300-more/100-editor-setup.mdx
>  ## Overview
@molebox Since you're working on this - could you replace Overview with `<TopBlock>` around everything before the first h2?

2021-04-06 07:45 UTC, mhwelander commented on content/200-concepts/300-more/100-editor-setup.mdx
> +> **Note**: Community projects are not maintained or officially supported by Prisma and some features may by out of sync. Use at your own discretion.
Nice 👍

2021-04-06 07:47 UTC, mhwelander commented
Looks good to me. :) Left 2 comments, otherwise SHIIIIPP IIIITTT

2021-04-06 08:07 UTC, merged