Relations troubleshooting: m-n self-relation
prisma/prisma2-docs pull request #2029
Opened 2021-07-13 13:53 UTC by mhwelander

2021-07-27 11:00 UTC, rahul3v requested changes

2021-07-27 11:00 UTC, rahul3v commented on content/200-concepts/100-components/01-prisma-schema/06-relations/500-troubleshooting-relations.mdx
>  There are a couple of ways to define a m-n relationship, implicitly or explicity. Implicitly means letting Prisma handle the relation table (JOIN table) under the hood, all you have to do is define a
```suggestion
There are a couple of ways to define a m-n relationship, implicitly or explicitly. Implicitly means letting Prisma handle the relation table (JOIN table) under the hood, all you have to do is define an array/list for the non scalar types on each model, see [implicit many-to-many relations](many-to-many-relations#implicit-many-to-many-relations).
```

2021-08-11 06:41 UTC, molebox approved these changes
Great example! And refreshing to read something that is not based around books, blogs 😅

2021-08-11 06:41 UTC, molebox commented on content/200-concepts/100-components/01-prisma-schema/06-relations/500-troubleshooting-relations.mdx
> +In the following implicit many-to-many self-relation, the lexicographic order of relation fields in `a_eats` (1) and `b_eatenBy` (2):
What a word! Lexicographic!
![picard-clapping](https://user-images.githubusercontent.com/22930449/128981333-f94287db-43eb-43e5-b867-d3ef63c9184f.gif)

2021-08-13 06:36 UTC, merged