MongoDB introspection quickstart
prisma/prisma2-docs pull request #2383
Opened 2021-10-04 09:58 UTC by pimeys

Replaces the MongoDB quickstart with instructions on how to introspect your data.

2021-10-04 10:43 UTC, pimeys commented on content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/125-introspection.mdx
> +This commands reads the `DATABASE_URL` environment variable that's defined in `.env` and connects to your database. Once the connection is established, it introspects the database (i.e. it _samples t
```suggestion
This command reads the `DATABASE_URL` environment variable that's defined in `.env` and connects to your database. Once the connection is established, it introspects the database (i.e. it _samples the data it finds_). It then translates the data it finds from MongoDB into a Prisma data model.
```

2021-10-04 10:46 UTC, Jolg42 commented on content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/125-introspection.mdx
> +Prisma introspects MongoDB schema by sampling the data stored in the given database. For the purpose of this guide, we'll create three collections and add some data to them. Either using the [mongo-e
```suggestion
Prisma introspects MongoDB schema by sampling the data stored in the given database. For the purpose of this guide, we'll create three collections and add some data to them. Either using  [Robo 3T](https://robomongo.org/) GUI or from [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) console, add a new database `prisma` and three collections: `Post`, `Profile` and `User`.
```

2021-10-04 10:47 UTC, Jolg42 commented on content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/125-introspection.mdx
> +Open the `prisma/schema.prisma` file and replace the default configurations with the following:
```suggestion
Open the `prisma/schema.prisma` file and replace the datasource and generator with the following:
```

2021-10-04 12:29 UTC, Jolg42 commented on content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/125-introspection.mdx
> +Prisma introspects a MongoDB schema by sampling the data stored in the given database. For the purpose of this guide, we'll create three collections and add some data to them. Either using  [Robo 3T]
```suggestion
Prisma introspects a MongoDB schema by sampling the data stored in the given database. For the purpose of this guide, we'll create three collections and add some data to them. Either using [Robo 3T](https://robomongo.org/) GUI or from [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) console, add a new database `prisma` and three collections: `Post`, `Profile` and `User`.
```

2021-10-05 10:13 UTC, Jolg42 commented on content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/125-introspection.mdx
> +
```suggestion
<Tip>
  We're constantly iterating on this feature, [so please provide feedback for introspecting MongoDB databases here](https://github.com/prisma/prisma/issues/8241).
</Tip>

## Introspect your MongoDB database with `prisma db pull`

```

2021-10-06 21:57 UTC, thebiglabasky requested changes
There's a bit of inconsistency using "you" and "we". We should stick to using "you" across the board (https://www.prisma.io/docs/about/prisma-docs/style-guide#use-you-as-the-pronoun)
Other than that it looks good

2021-10-06 21:57 UTC, thebiglabasky commented on content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/125-introspection.mdx
> +Next add some posts to our `Post` collection. It's important that the ObjectID in `userId` matches the user you created above.
```suggestion
Next, add some posts to our `Post` collection. It's important that the ObjectID in `userId` matches the user you created above.
```

2021-10-07 07:39 UTC, nikolasburk commented on content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/125-introspection.mdx
> +```sh
Maybe add copy-button here:

```suggestion
```sh copy
```

2021-10-07 09:25 UTC, nikolasburk commented on content/100-getting-started/02-setup-prisma/200-add-to-existing-project/120-mongodb/125-introspection.mdx
> +## Setting up your Database
I think it might be confusing that the section "Add to existing project" in which this guide is located in instructs the user to set up their DB. Maybe it's worth highlighting that this is only for the purpose of demonstrating introspection but generally a reader who will come here probably can be expected to already have a DB?

2021-10-07 21:42 UTC, merged

2021-10-07 21:42 UTC, matthewmueller commented
Thanks everyone!