Edit troubleshooting-relations doc
prisma/prisma2-docs pull request #2468
Opened 2021-11-03 20:14 UTC by tanberry

Added a section about the problem of enforced primary key DBs not working with implicit syntax, for m-n relations.

2021-11-04 14:17 UTC, keerlu commented
One thing I noticed from the preview is that the documentation uses a mix of 'many-to-many' and 'm-n' terminology, which is a little confusing to me. It looks like 'many-to-many' is being used at the point the concept is introduced in the documentation, e.g. https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations, and for the majority of subheadings, so that may be the best option.

Also unsure of capitalisation for 'Join table' - the linked doc has 'JOIN table' so might want to be consistent.

Otherwise looks good to me

2021-11-04 15:11 UTC, janpio commented
In Prisma context the Join table is usually called "relation table".

2021-11-04 15:29 UTC, albertoperdomo requested changes

2021-11-04 15:29 UTC, albertoperdomo commented on content/200-concepts/100-components/01-prisma-schema/06-relations/500-troubleshooting-relations.mdx
> +If your database provider automatically creates a primary key, and you want to use m-n relations, you need to use explicit relation syntax, manually create the join model, and verify that this join m
Same comment as in the other PR. https://github.com/prisma/docs/pull/2469#pullrequestreview-797898457

```suggestion
You need to use explicit relation syntax, manually create the join model, and verify that this join model has a primary key. 
```

2021-11-04 15:29 UTC, albertoperdomo commented on content/200-concepts/100-components/01-prisma-schema/06-relations/500-troubleshooting-relations.mdx
> +If your database provider automatically creates a primary key, and you want to use m-n relations, you need to use explicit relation syntax, manually create the join model, and verify that this join m
I think we should consider adding a link to the explicit relation syntax, here, perhaps? Unless it's really easy to navigate to (scroll up or down to a section that is close).

2021-11-08 08:13 UTC, janpio approved these changes

2021-11-08 23:07 UTC, merged