Update 01-migrate-from-typeorm.mdx
prisma/prisma2-docs pull request #2469
Opened 2021-11-03 20:41 UTC by tanberry

Added warning at the bottom of this topic, in section about implicit syntax is m-n relations, about the enforced primary key issue. See [Issue #958](https://github.com/prisma/docs/issues/958).

2021-11-04 14:29 UTC, keerlu commented
Wondering if this admonition should be earlier in the document (e.g. before 'Here is an example with TypeORM') so that people reading this subsection definitely see it

2021-11-04 15:14 UTC, janpio commented
My 2c: `database provider automatically creates a primary key` is pretty uncommon, so an edge case.

2021-11-04 15:27 UTC, albertoperdomo requested changes

2021-11-04 15:27 UTC, albertoperdomo commented on content/300-guides/400-migrate-to-prisma/01-migrate-from-typeorm.mdx
> +If your database provider automatically creates a primary key, and you want to use m-n relations, you need to use explicit relation syntax, manually create the join model, and verify that this join m
I may be wrong but I think 

>If your database provider automatically creates a primary key,

should be

>If your database provider requires tables to have primary keys,

Some providers like DigitalOcean enforce primary keys on all tables for replication. In such a case, the user would have to switch to the explicit syntax.

2021-11-08 08:14 UTC, janpio approved these changes

2021-11-08 13:55 UTC, merged