Clarify what is 'mydb'
prisma/prisma2-docs pull request #3001
Opened 2022-03-22 19:43 UTC by Gui-Alucard

Is just an improvement to help those are new with technology

## Describe this PR

## Changes

## What issue does this fix?

## Any other relevant information

2022-03-22 19:50 UTC, janpio requested changes
`mydv` is the database in MySQL context, not a schema. Schemas do not really exist there.

2022-03-22 20:13 UTC, Gui-Alucard commented
> 

If you are using MySQL Workbench, then where is 'mydb' you need to type the name of the schema to connect. I just tried that e decide to bring this up.

2022-03-22 20:21 UTC, janpio commented
That is unfortunate and confusing wording from MySQL, which unfortunately is all over the place. In their docs they also call the `mysql` database a "schema", or say things like "INFORMATION_SCHEMA is a database" further muddling the two terms.

From Prisma perspective MySQL only has the concept of a "database" that is defined after the hostname in the connection string.

2022-03-22 20:55 UTC, Gui-Alucard commented
> That is unfortunate and confusing wording from MySQL, which unfortunately is all over the place. In their docs they also call the `mysql` database a "schema", or say things like "INFORMATION_SCHEMA is a database" further muddling the two terms.
> 
> From Prisma perspective MySQL only has the concept of a "database" that is defined after the hostname in the connection string.

I wrote a note about that though.

2022-03-23 17:27 UTC, tanberry commented on content/100-getting-started/02-setup-prisma/100-start-from-scratch/110-relational-databases/100-connect-your-database.mdx
> +  > **_NOTE:_**  In MySQL docs the mysql database ('mydb' in this case) is called as "schema" too.
```suggestion
  > **_NOTE:_**  In MySQL documentation the MySQL database ('mydb' in this case) is labeled as "schema" too.
```

2022-03-23 17:28 UTC, tanberry commented
Thanks @Gui-Alucard for your help in clarifying this! I did tweak your wording a little; if you are ok with that change please add it and then we can merge this PR. Sound ok to you @janpio?

2022-03-23 22:27 UTC, janpio commented
No, this is not correct unfortunately. They only call the `mysql` database (which is the system database which has a specific function) a schema. Both the current suggestion from @Gui-Alucard and your edit suggestion make it sound like if the "database" was a "schema" - and that is not the case. Sorry.

2022-03-24 11:50 UTC, Gui-Alucard commented
> No, this is not correct unfortunately. They only call the `mysql` database (which is the system database which has a specific function) a schema...

I followed this suggestion and did a new commit. I am concerned that I've been naughty and causing problems, I just wanted to clear things up for new developers.

2022-03-24 13:06 UTC, janpio commented
You are not naughty or causing problems at all, I just do not agree with the way you phrase this. For me (and according to MySQL documentation) in generall what comes after the hostname is a "database". (It might work a bit like PostgreSQL schemas, but it is still called "database" in context of MySQL usually. Unfortunately there is some inconsistency in tools like MySQL Workbench or on some special databases in their documentation - but nothing that implies that you generally call the things which has the value "mydb" here a "schema")

2022-03-24 18:44 UTC, Gui-Alucard commented
I agree with you and understand your point. So, seeing that (MySQL inconsistency) like a limitation I will close this PR though.

2022-03-24 18:44 UTC, closed without merging

2022-03-24 19:08 UTC, janpio commented
Thanks for understanding. When we ever understand the terminology properly, we might write a page in our [DataGuide](https://www.prisma.io/dataguide/) and link to it from everywhere. But right now we are still pretty much confused ourselves about the inconsistencies.