Edit Client methods into sentence
prisma/prisma2-docs pull request #3233
Opened 2022-06-06 15:25 UTC by tanberry

Edited to try to make more clear that "Client-level" means any methods that interact with the Prisma Client.

2022-06-06 15:48 UTC, keerlu reviewed
'Interact' isn't quite the right word, it's the client that is doing the method. E.g. for `client.$disconnect` the client is doing the disconnecting. Not sure how you want to phrase that...

2022-06-06 20:55 UTC, janpio commented
The current sentence differentiates "Client level" from "model level" I think. You have stuff that is about the models from your schema, and you have stuff that is disconnected from that and lives one level higher - the connection lifecycle things, but also Client things like middlewares and logging, or the raw methods or transactions.

2022-06-20 16:01 UTC, tanberry commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +Methods that interact with the Prisma Client are prefixed by `$`.
```suggestion
Client-level methods (that is, methods executed by the Prisma Client) are prefixed by `$`.
```

2022-06-20 16:06 UTC, janpio requested changes
See comment

2022-06-20 16:30 UTC, tanberry commented
> 

@janpio  I saw your comment, which is why I left the phrase "Client-level, then explained what that means in the parentheses. Let me know if you have exact preferred wording; I'd like to close this PR. ;-)

2022-06-20 17:19 UTC, janpio commented
It does not mean what you added in the parens.

From my previous comment:

> You have stuff that is about the models from your schema, and you have stuff that is disconnected from that and lives one level higher - the connection lifecycle things, but also Client things like middlewares and logging, or the raw methods or transactions.

That is meant as "Client level" here vs. the model level functionality, that lives under `prisma.modelname.*`.

2023-06-20 12:47 UTC, closed without merging