Remove Support menu option in Docs
prisma/prisma2-docs pull request #3270
Opened 2022-06-14 19:56 UTC by tanberry

Removing the Support menu option from the Docs top menu.

2022-06-18 11:30 UTC, janpio requested changes
Generally looks good, most of the renames were recognized by GitHub.

Because of the additional text changes, the ones for the index pages were _not_, but that should not be a big deal.

What is missing are the necessary redirects. Those are needed before this can be merged so the old URLs keep working.

Also, for me the new location and URL is unexpected. You just started to only put database specific (databases and providers) into the "database guides" folders, and this is now something completely different again.

(Ah, just now noticed that this is still marked as draft - but I got a review request already. Hope this was intended.)

2022-06-20 16:44 UTC, tanberry commented
Yes, thanks for your review @Jan, very much intended. and YYes,I know I needed a redirect, just hadn't gotten to it yet. That PR is now created and ready... I'd like to merge them both asap... Idid see your comment about the location... those changes you mentioned will be part of the upcoming Info Architecture work; this is a quick fix to remove the Support page.

2022-06-20 16:55 UTC, janpio commented on content/300-guides/050-database/880-troubleshooting-orm/index.mdx
> +Refer to our [Support site](https://www.prisma.io/support/) for full information about getting help.
No trailing slash on this URL:
```suggestion
Refer to our [Support site](https://www.prisma.io/support) for full information about getting help.
```

2022-06-20 17:13 UTC, janpio approved these changes
Actually unreviewed as redirects PR separate.

2022-06-20 18:20 UTC, merged