fix: rename deleteAll() to deleteMany()
prisma/prisma2-docs pull request #3370
Opened 2022-07-04 12:30 UTC by Jolg42

Since `deleteAll()` method doesn't exist

2022-07-06 19:11 UTC, janpio approved these changes

2022-07-06 19:12 UTC, janpio requested changes
Visual before/after for the Admonition: 
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/183673/177625385-d9ce1bed-3d15-4244-9525-181948399908.png">

2022-07-07 08:17 UTC, Jolg42 commented on content/200-concepts/100-components/01-prisma-schema/06-relations/425-referential-actions/index.mdx
> +
```suggestion

```

2022-07-07 18:26 UTC, janpio approved these changes

2022-07-14 21:22 UTC, tanberry commented
Thank you @Jolg42 !!

2022-07-14 21:22 UTC, merged