Update 064-custom-models.mdx
prisma/prisma2-docs pull request #3503
Opened 2022-07-23 15:18 UTC by muddledluck

In extending Prisma client through function 
```return Object.assign(prisma, {``` should be ```return Object.assign(prisma.user, {```
because when we try to use `Users` like

```
const prisma = new PrismaClient();

const user = Users(prisma.user)

async function getUser(email){
     const userExists = user.findFirst({
        where: { email: email }
     })
}
```

gives error 
says 
```
Property 'findFirst' does not exist on type 'PrismaClient<PrismaClientOptions, never, RejectOnNotFound | RejectPerOperation | undefined> & { ...; }'
```

So, for this we need to update 
```return Object.assign(prisma, {```
to
```return Object.assign(prisma.user, {```

Otherwise, we should go like this

```
const prisma = new PrismaClient();

const user = Users(prisma.user)

async function getUser(email){
     const userExists = user.user.findFirst({
        where: { email: email }
     })
}

async function signUp(data){
     const userExists = user.signUp(data)
}
```

## Describe this PR

## Changes

## What issue does this fix?

## Any other relevant information

2022-07-23 15:19 UTC, muddledluck commented
@all-contributors please add @muddledluck for doc

2022-07-29 18:02 UTC, tanberry commented
Thanks so much for catching this @muddledluck ! We are going to run a quick tech review on it and get it merged (along with your contributors PR!).

2022-07-29 19:01 UTC, millsp approved these changes

2022-07-29 19:07 UTC, millsp commented on content/200-concepts/100-components/02-prisma-client/064-custom-models.mdx
> +  return Object.assign(prisma.user, {
```suggestion
  return Object.assign(prismaUser, {
```

2022-07-29 19:09 UTC, millsp requested changes, later dismissed
It will be better to keep the variable (thanks @janpio)

2022-07-29 19:09 UTC, millsp commented on content/200-concepts/100-components/02-prisma-client/064-custom-models.mdx
> +  return Object.assign(prisma.user, {
```suggestion
  return Object.assign(prismaUser, {
```

2022-07-29 20:15 UTC, merged

2022-07-29 20:16 UTC, tanberry commented
Thanks again @muddledluck !

2022-07-29 20:18 UTC, muddledluck commented
My pleasure @tanberry 😁

2022-07-29 20:23 UTC, muddledluck commented
one question, when does this change visible on https://www.prisma.io/docs/concepts/components/prisma-client/custom-models ?
@tanberry