Update 085-query-optimization-performance.mdx
prisma/prisma2-docs pull request #4049
Opened 2022-11-11 19:19 UTC by BauerBr

## Describe this PR

Small typos in the query and optimization performance documentation

2022-11-16 11:08 UTC, andrew-walford-prisma requested changes

2022-11-16 11:08 UTC, andrew-walford-prisma commented on content/300-guides/100-performance-and-optimization/085-query-optimization-performance.mdx
> +You can use `include` to return each user's posts, that only results in **two** SQL queries - one to get users, and one to get posts. This is known as a [nested read](/concepts/components/prisma-clie
```suggestion
You can use `include` to return each user's posts. This only results in **two** SQL queries - one to get users, and one to get posts. This is known as a [nested read](/concepts/components/prisma-client/relation-queries#nested-reads).
```

Thanks @BauerBr . I suggest a small tweak to your proposed change.

2022-11-17 08:52 UTC, janpio approved these changes

2022-11-17 09:00 UTC, andrew-walford-prisma approved these changes

2022-11-17 11:00 UTC, merged