Update 03-generators.mdx
prisma/prisma2-docs pull request #4089
Opened 2022-11-20 17:47 UTC by EndyKaufman

Append new generator for NestJS

## Describe this PR

## Changes

## What issue does this fix?

## Any other relevant information

2023-01-13 10:59 UTC, janpio commented on content/200-concepts/100-components/01-prisma-schema/03-generators.mdx
> +- [`typegraphql-prisma-nestjs`](https://github.com/EndyKaufman/typegraphql-prisma-nestjs#readme): Fork of Generates [TypeGraphQL](https://github.com/MichalLytek/typegraphql-prisma) CRUD resolvers for
```suggestion
- [`typegraphql-prisma-nestjs`](https://github.com/EndyKaufman/typegraphql-prisma-nestjs#readme): Fork of [TypeGraphQL](https://github.com/MichalLytek/typegraphql-prisma), which also generates CRUD resolvers for Prisma models but for NestJS
```

2023-05-22 16:46 UTC, EndyKaufman commented
@janpio

2023-05-30 13:32 UTC, jharrell commented on content/200-concepts/100-components/01-prisma-schema/03-generators.mdx
> +- [`typegraphql-prisma-nestjs`](https://github.com/EndyKaufman/typegraphql-prisma-nestjs#readme): Fork of [TypeGraphQL](https://github.com/MichalLytek/typegraphql-prisma), which also generates CRUD r
```suggestion
- [`typegraphql-prisma-nestjs`](https://github.com/EndyKaufman/typegraphql-prisma-nestjs#readme): Fork of [`typegraphql-prisma`](https://github.com/MichalLytek/typegraphql-prisma), which also generates CRUD resolvers for Prisma models but for NestJS
```

2023-05-30 13:33 UTC, jharrell requested changes
Sorry to nitpick, but let's be a bit more specific and say that this is a fork of `typegraphql-prisma`

2023-05-30 13:34 UTC, EndyKaufman commented on content/200-concepts/100-components/01-prisma-schema/03-generators.mdx
> +- [`typegraphql-prisma-nestjs`](https://github.com/EndyKaufman/typegraphql-prisma-nestjs#readme): Fork of [TypeGraphQL](https://github.com/MichalLytek/typegraphql-prisma), which also generates CRUD r
ok

2023-05-30 13:41 UTC, jharrell approved these changes

2023-06-13 20:04 UTC, EndyKaufman commented
@ruheni

2023-06-14 08:42 UTC, merged