workaround when using pnpm/pnpx
prisma/prisma2-docs pull request #4134
Opened 2022-11-25 19:12 UTC by delight

## Describe this PR

When working with pnpm/pnpx there is a problem while prisma generate is run. 

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
npm ERR! Cannot read properties of null (reading 'matches')
```
workaround is to do a pnpm i  @prisma/client before running migrate (generate)

## Changes

Adds a little side note into the quickstart 

## What issue does this fix?
See PR description
## Any other relevant information

don't know if that is the right place to add this information - but it certainly would help others running into this problem

2022-11-25 19:49 UTC, janpio requested changes
This is actually related to a bug in Prisma CLI, so we should fix that.

2022-11-25 20:11 UTC, delight commented
> This is actually related to a bug in Prisma CLI, so we should fix that.

Is there an issue for that bug ?

2022-11-25 21:35 UTC, janpio commented
Multiple: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+pnpm%22+sort%3Aupdated-desc+

If you think your situation is not represented or could be better, feel free to open a new one though.

2023-11-16 15:51 UTC, nikolasburk commented
@delight thanks for opening this PR. Since it seems like this is a bug in the Prisma CLI, I'm closing this PR. Let me know if you still feel it's relevant and we can re-open it 🙏 

Thanks a lot for taking the time to make our documentation better, this is much appreciated 💚

2023-11-16 15:51 UTC, closed without merging