Update 200-one-to-many-relations.mdx
prisma/prisma2-docs pull request #4432
Opened 2023-01-19 14:37 UTC by sliepe

## Describe this PR

- Wrong description for a following example

## Changes

- Corrected description for a following example

## What issue does this fix?

- N/A

## Any other relevant information

- https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-many-relations#mongodb
  - ~~Wrong~~: "The following list of Post MongoDB documents each have a ~~userId~~ field which reference the same user:"
  - **Right**: "The following list of Post MongoDB documents each have a **authorId** field which reference the same user:"

2023-01-22 15:17 UTC, sliepe reviewed
Simply approve please

2023-01-25 15:07 UTC, zachtil requested changes

2023-01-25 15:07 UTC, zachtil commented on content/200-concepts/100-components/01-prisma-schema/06-relations/200-one-to-many-relations.mdx
> +The following list of `Post` MongoDB documents each have a `authorId` field which reference the same user:
```suggestion
Each of the following `Post` MongoDB documents has an `authorId` field which references the same user:
```

2023-02-14 09:23 UTC, sliepe commented on content/200-concepts/100-components/01-prisma-schema/06-relations/200-one-to-many-relations.mdx
> +The following list of `Post` MongoDB documents each have a `authorId` field which reference the same user:
Sorry for too late.

2023-11-16 11:08 UTC, merged

2023-11-16 11:08 UTC, nikolasburk commented
This makes sense, thanks for caring about our documentation @sliepe 🙏 💚