feat: update `binaryTargets` reference for Linux Alpine arm64
prisma/prisma2-docs pull request #4488
Opened 2023-02-03 15:45 UTC by jkomyno

## Describe this PR

## Changes

- update `binaryTargets`'s reference to reflect the newest Linux Alpine arm64 support
- specify that Prisma supports `x86_64` architectures by default

## What issue does this fix?

Contributes to https://github.com/prisma/prisma/issues/8478

2023-02-03 16:08 UTC, janpio commented on content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
> +| `map`       | **No**   | `String`  |
Accidental removal?

2023-02-03 16:08 UTC, janpio commented on content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
> +| `sort`      | **No**   | `String`  | Allows you to specify in what order the entries of the ID are stored in the database. The available options are `Asc` and `Desc`.<br /><br />In preview in versi
Also accidental removal?

2023-02-03 16:08 UTC, janpio commented on content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
> +| `clustered` | **No**   | `Boolean`          | Defines whether the ID is clustered or non-clustered. Defaults to `true`.<br /><br />SQL Server only. In preview in versions 3.13.0 and later, and in g
Same here.

2023-02-03 16:08 UTC, janpio commented on content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
> +| `references` | `FieldReference[]` | On [annotated](/concepts/components/prisma-schema/relations#annotated-relation-fields-and-relation-scalar-fields) relation fields | A list of [fields](/concepts/
Same here.

2023-02-03 16:09 UTC, janpio commented on content/400-reference/200-api-reference/100-prisma-schema-reference.mdx
> +| MySQL       | `INT`           |
Accidental?

2023-02-03 16:09 UTC, janpio approved these changes
Actual `binaryTargets` look good.

2023-02-03 16:09 UTC, janpio requested changes
Unrelated changes seem problematic.

2023-02-05 23:48 UTC, jkomyno commented
> Unrelated changes seem problematic.

That looks like some troubles when using Github's UI for editing the docs. Will clone the repo locally and push a new PR.

2023-02-06 10:50 UTC, jkomyno commented
Deprecated by https://github.com/prisma/docs/pull/4491

2023-02-06 10:50 UTC, closed without merging