Revises multiple locations describing compound IDs and unique constraints
prisma/prisma2-docs pull request #4591
Opened 2023-03-24 03:00 UTC by sabinadams

Closes #4588

This PR does a few things:

1. Removes the [existing section](https://www.prisma.io/docs/concepts/components/prisma-client/crud#get-record-by-compound-id-or-compound-unique-identifier) describing how to query using a Compound ID and/or Compound Unique Constraint 
2. Adds a clarifying message to the [`@@id` section](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-an-id-field) about the resulting field's name
3. Adds a clarifying message to the [`@@unique` section](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-a-unique-field) about the resulting field's name
4. Adds a new page dedicated to using composite IDs and unique constraints in Prisma Client queries

2023-03-24 03:01 UTC, sabinadams commented
@janpio Made a pretty sizeable change to multiple locations relating to `@@id` and `@@unique`. Let me know what you think!

2023-05-12 12:53 UTC, nikolasburk requested changes

2023-05-12 12:53 UTC, nikolasburk commented on content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
> +Refer to the documentation on [working with composite IDs](/concepts/components/prisma-client/working-with-fields/working-with-composite-ids) to learn how to interact with a composite ID in Prisma Cl
the link here seems to be broken

2023-05-12 12:53 UTC, nikolasburk commented on content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
> +Refer to the documentation on [working with composite IDs](/concepts/components/prisma-client/working-with-fields/working-with-composite-ids) to learn how to interact with a composite ID in Prisma Cl
I guess it should point to this page: https://docs-git-compound-id-unique-id-section-prisma.vercel.app/concepts/components/prisma-client/working-with-fields/working-with-composite-ids-and-constraints

2023-05-12 12:53 UTC, nikolasburk commented on content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
> +Refer to the documentation on [working with composite unique identifiers](/concepts/components/prisma-client/working-with-fields/working-with-composite-ids) to learn how to interact with a composite
broken link, probably should link here: https://docs-git-compound-id-unique-id-section-prisma.vercel.app/concepts/components/prisma-client/working-with-fields/working-with-composite-ids-and-constraints

2023-05-12 12:53 UTC, nikolasburk commented on content/200-concepts/100-components/02-prisma-client/051-working-with-fields/300-working-with-composite-ids-and-constraints.mdx
> +Querying for record from the `Like` table would yield results that look like the following:
- "Querying for record" -> bad grammar
- why don't we show a query here? wouldn't that be the most relevant thing to show at this point?

2023-05-12 12:53 UTC, nikolasburk commented on content/200-concepts/100-components/02-prisma-client/051-working-with-fields/300-working-with-composite-ids-and-constraints.mdx
> +    likeId: {
I find the connection between this `likeId` and the custom name from before not strong enough. Ideally I'd like to see Prisma Client examples for _both_ scenarios: the one where a custom name is used and one where the default name is used.

2023-11-23 16:06 UTC, nikolasburk commented on content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
> +Refer to the documentation on [working with composite IDs](/concepts/components/prisma-client/working-with-fields/working-with-composite-ids) to learn how to interact with a composite ID in Prisma Cl
```suggestion
Refer to the documentation on [working with composite IDs](/concepts/components/prisma-client/working-with-fields/working-with-composite-ids-and-constraints) to learn how to interact with a composite ID in Prisma Client.
```

2023-11-23 16:07 UTC, nikolasburk commented on content/200-concepts/100-components/01-prisma-schema/04-data-model.mdx
> +Refer to the documentation on [working with composite unique identifiers](/concepts/components/prisma-client/working-with-fields/working-with-composite-ids) to learn how to interact with a composite
```suggestion
Refer to the documentation on [working with composite unique identifiers](/concepts/components/prisma-client/working-with-fields/working-with-composite-ids-and-constraints) to learn how to interact with a composite unique constraints in Prisma Client.
```

2023-11-23 16:07 UTC, nikolasburk commented on content/200-concepts/100-components/02-prisma-client/051-working-with-fields/300-working-with-composite-ids-and-constraints.mdx
> +Querying for record from the `Like` table would yield results that look like the following:
```suggestion
Querying for records from the `Like` table would yield results that look like the following:
```

2023-11-23 16:11 UTC, nikolasburk commented on content/200-concepts/100-components/02-prisma-client/051-working-with-fields/300-working-with-composite-ids-and-constraints.mdx
> +Querying for records from the `Like` table would yield results that look like the following:
```suggestion
Querying for records from the `Like` table (e.g. using `prisma.like.findMany()`) would return objects that look as folllows:
```

2023-11-23 16:20 UTC, nikolasburk approved these changes

2023-11-23 16:20 UTC, nikolasburk approved these changes

2023-11-23 16:20 UTC, merged

2023-11-23 16:20 UTC, nikolasburk commented
Thanks @sabinadams 😉 hope you're doing well! 💚