Update 100-connect-your-database.mdx
prisma/prisma2-docs pull request #4633
Opened 2023-04-02 16:24 UTC by GNVageesh

## Describe this PR

`relatioMode` attribute is no more required

## Changes

The `relationMode` attribute in the `datasource` is not required for version 4.12.0 onwards

2023-04-03 11:44 UTC, janpio commented
Uhm yes it is? Only the preview feature flag got removed some versions ago. Using Prisma with a PlanetScale database still requires `relationMode=prisma`.

2023-04-03 11:44 UTC, janpio requested changes
Uhm yes it is? Only the preview feature flag got removed some versions ago. 
Using Prisma with a PlanetScale database still requires relationMode=prisma.

2023-04-03 18:38 UTC, GNVageesh commented
But with one of my recent projects, ignoring the line `relationMode = "prisma"` in the `datasource` block, passed without any errors. I am using Prisma version `4.12.0`. 
So does it make `relationMode` optional?

2023-04-03 21:44 UTC, janpio commented
Are you using relations in that project?
`relationMode` is only required if you want to use relations and migrate those on PlanetScale.

2023-04-04 14:03 UTC, GNVageesh commented
My apologies for not understanding the concept adequately and opening a pull request. Yes, you are right, `relationMode` is only required when we have relations in our schema. Else it is not required.
Thanks for getting it into the light. Once again, my apologies.

2023-04-04 14:51 UTC, janpio commented
All good. Thanks for spending the time here!

2023-04-04 14:51 UTC, closed without merging