add new Supabase quick guide
prisma/prisma2-docs pull request #4740
Opened 2023-05-03 19:12 UTC by jharrell

## Describe this PR

Added a (brief) guide to setting up Supabase with Prisma

## Changes

- added 880-supabase.mdx

## What issue does this fix?

fixes #2762

2023-05-03 19:25 UTC, sabinadams requested changes
Just left a couple SUPER SMALL changes. Good stuff!

2023-05-03 19:25 UTC, sabinadams commented on content/300-guides/050-database/880-supabase.mdx
> +This document discusses the concepts behind using Prisma and Supabase, explains the commonalities and differences between Supabase and other database providers, and leads you through the process for
```suggestion
This guide discusses the concepts behind using Prisma and Supabase, explains the commonalities and differences between Supabase and other database providers, and leads you through the process for configuring your application to integrate with Supabase.
```

2023-05-03 19:25 UTC, sabinadams commented on content/300-guides/050-database/880-supabase.mdx
> +To learn more about Supabase, you can check out their Architecture [here](https://supabase.com/docs/guides/getting-started/architecture) and features [here](https://supabase.com/docs/guides/getting-s
```suggestion
To learn more about Supabase, you can check out their architecture [here](https://supabase.com/docs/guides/getting-started/architecture) and features [here](https://supabase.com/docs/guides/getting-started/features)
```

2023-05-04 06:35 UTC, nikolasburk requested changes

2023-05-04 06:35 UTC, nikolasburk commented on content/300-guides/050-database/880-supabase.mdx
> +## Getting Started with Supabase
Since we typically use sentence casing for section headings, this should be lowercased

```suggestion
## Getting started with Supabase
```

2023-05-04 06:35 UTC, nikolasburk commented on content/300-guides/050-database/880-supabase.mdx
> +Supabase is an open source Firebase alternative providing all the backend features you need to build a product. Unlike Firebase, Supabase is backed by PostgreSQL which can be accessed directly.
```suggestion
[Supabase](https://supabase.com/) is a PostgreSQL hosting servier and open source Firebase alternative providing all the backend features you need to build a product. Unlike Firebase, Supabase is backed by PostgreSQL which can be accessed directly using Prisma.
```

2023-05-04 06:36 UTC, nikolasburk commented
This looks great! I've left some minor suggestions but once these are in, the PR is ready to get merged 🚀 great job, Jon! 👏

2023-05-04 14:47 UTC, nikolasburk approved these changes

2023-05-04 15:52 UTC, sabinadams approved these changes

2023-05-04 17:01 UTC, merged