orderByNulls is now GA
prisma/prisma2-docs pull request #4913
Opened 2023-06-14 14:31 UTC by Jolg42

Closes https://github.com/prisma/docs/issues/4853

2023-06-14 14:43 UTC, ruheni approved these changes

2023-06-14 19:00 UTC, janpio commented on content/200-concepts/100-components/02-prisma-client/050-filtering-and-sorting.mdx
> +This feature is generally available in version `4.16.0` and later. It was first added as a [Preview feature](/concepts/components/preview-features) in version [`4.1.0`](https://github.com/prisma/pris
Missing the preview feature needed to enable the feature.

2023-06-14 19:00 UTC, janpio commented on content/200-concepts/100-components/02-prisma-client/050-filtering-and-sorting.mdx
>  Note: Prisma Client does not support this feature for MongoDB.
I think we usually split the version info and feature limitations in different admonitions.

2023-06-20 10:56 UTC, janpio requested changes
See existing comments.

2023-06-20 11:39 UTC, janpio commented on content/200-concepts/100-components/02-prisma-client/050-filtering-and-sorting.mdx
> +To use this feature in versions [`4.1.0`](https://github.com/prisma/prisma/releases/tag/4.1.0) to [`4.15.0`](https://github.com/prisma/prisma/releases/tag/4.15.0) the [Preview feature](/concepts/comp
```suggestion
This feature is generally available in version `4.16.0` and later. To use this feature in versions [`4.1.0`](https://github.com/prisma/prisma/releases/tag/4.1.0) to [`4.15.0`](https://github.com/prisma/prisma/releases/tag/4.15.0) the [Preview feature](/concepts/components/preview-features/client-preview-features#enabling-a-prisma-client-preview-feature) `orderByNulls` will need to be enabled.
```

2023-06-20 11:51 UTC, janpio approved these changes

2023-06-20 14:07 UTC, merged