make filteredRelationCount GA
prisma/prisma2-docs pull request #4914
Opened 2023-06-14 14:39 UTC by Jolg42

Closes https://github.com/prisma/docs/issues/4855

2023-06-14 14:44 UTC, ruheni approved these changes

2023-06-14 15:50 UTC, janpio commented on content/200-concepts/100-components/02-prisma-client/055-aggregation-grouping-summarizing.mdx
> +This feature is generally available in version `4.16.0` and later. It was first added as a [Preview feature](/concepts/components/preview-features) in version [`4.3.0`](https://github.com/prisma/pris
Missing the preview feature flag with which users of 4.3.0 to 4.16.0 can use it.

2023-06-14 15:51 UTC, Jolg42 commented on content/200-concepts/100-components/02-prisma-client/055-aggregation-grouping-summarizing.mdx
> +This feature is generally available in version `4.16.0` and later. It was first added as a [Preview feature](/concepts/components/preview-features) in version [`4.3.0`](https://github.com/prisma/pris
It's unclear how we should handle this from looking at other preview features now GA to me.

2023-06-14 15:52 UTC, Jolg42 commented on content/200-concepts/100-components/02-prisma-client/055-aggregation-grouping-summarizing.mdx
> +This feature is generally available in version `4.16.0` and later. It was first added as a [Preview feature](/concepts/components/preview-features) in version [`4.3.0`](https://github.com/prisma/pris
I mean, if someone who knows the docs better could figure it out, it would be great.

2023-06-14 16:02 UTC, jharrell commented on content/200-concepts/100-components/02-prisma-client/055-aggregation-grouping-summarizing.mdx
> +This feature is generally available in version `4.16.0` and later. It was first added as a [Preview feature](/concepts/components/preview-features) in version [`4.3.0`](https://github.com/prisma/pris
```suggestion
This feature is generally available in version `4.16.0` and later. 

To use this feature in versions [`4.3.0`](https://github.com/prisma/prisma/releases/tag/4.3.0) to [`4.15.0`](https://github.com/prisma/prisma/releases/tag/4.15.0) the [Preview feature](/concepts/components/preview-features/client-preview-features#enabling-a-prisma-client-preview-feature) `filteredRelationCount` will need to be enabled.
```

Something like this?

2023-06-20 10:56 UTC, janpio requested changes
See existing comments

2023-06-20 11:39 UTC, janpio commented on content/200-concepts/100-components/02-prisma-client/055-aggregation-grouping-summarizing.mdx
> +To use this feature in versions [`4.3.0`](https://github.com/prisma/prisma/releases/tag/4.3.0) to [`4.15.0`](https://github.com/prisma/prisma/releases/tag/4.15.0) the [Preview feature](/concepts/comp
```suggestion
This feature is generally available in version `4.16.0` and later. To use this feature in versions [`4.3.0`](https://github.com/prisma/prisma/releases/tag/4.3.0) to [`4.15.0`](https://github.com/prisma/prisma/releases/tag/4.15.0) the [Preview feature](/concepts/components/preview-features/client-preview-features#enabling-a-prisma-client-preview-feature) `filteredRelationCount` will need to be enabled.
```

2023-06-20 11:51 UTC, janpio approved these changes

2023-06-20 14:09 UTC, merged