Add note about `rejectOnNotFound` removal
prisma/prisma2-docs pull request #5018
Opened 2023-07-08 07:07 UTC by ruheni

Closes #4999

2023-07-08 08:19 UTC, janpio requested changes, later dismissed
`rejectOnNotFound` is also mentioned in the query documentation and needs to be marked removed there as well.

Additionally, this is the absolute minimum we can do here. I would greatly appreciate if we would find a way to de-emphasize the `rejectOnNotFound` content (especially the global config one).

2023-07-11 07:17 UTC, ruheni commented
I might be missing something, but I could only find it in the Reference after a global search. 🤔 

Could you point me to the page you're referring to?

2023-07-11 09:28 UTC, janpio commented
There are more mentions of `rejectOnNotFound` further down. You only added a note to the global usage of the feature in `PrismaClient` context.

2023-07-11 10:20 UTC, ruheni commented
Thanks. I've made the update. 💚

> I just realized I'd made the update on the wrong branch but it should be reflected now

2023-07-11 12:59 UTC, janpio commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +| `rejectOnNotFound` (deprecated) | `RejectOnNotFound`       | No       | If true, throw a `NotFoundError: No User found error`. <br></br>**Note:** `rejectOnNotFound`is deprecated in v4.0.0. From v4.
```suggestion
| `rejectOnNotFound` (deprecated) | `RejectOnNotFound`       | No       | If true, throw a `NotFoundError: No User found error`. <br></br>**Note:** `rejectOnNotFound` is deprecated in v4.0.0. From v4.0.0, use [`findUniqueOrThrow`](#finduniqueorthrow) instead.                                  |
```

2023-07-11 12:59 UTC, janpio commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +| `rejectOnNotFound` (deprecated) | `RejectOnNotFound`       | No       | If true, throw a `NotFoundError: No User found error`. <br></br>**Note:** `rejectOnNotFound`is deprecated in v4.0.0. From v4.
In the first column it still says "deprecated". It is now removed instead.
This is also still missing the information _when_ the functionality was removed.

2023-07-11 13:03 UTC, janpio commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +| `rejectOnNotFound` (deprecated) | `RejectOnNotFound`                                           | No       | If true, throw a `NotFoundError: No User found error`. <br></br>**Note:** `rejectOnNotFou
```suggestion
| `rejectOnNotFound` (deprecated) | `RejectOnNotFound`                                           | No       | If true, throw a `NotFoundError: No User found error`. <br></br>**Note:** `rejectOnNotFound` is deprecated in v4.0.0. From v4.0.0, use [`findFirstOrThrow`](#findfirstorthrow) instead.                                                     |
```

2023-07-11 13:03 UTC, janpio commented on content/400-reference/200-api-reference/050-prisma-client-reference.mdx
> +| `rejectOnNotFound` (deprecated) | `RejectOnNotFound`                                           | No       | If true, throw a `NotFoundError: No User found error`. <br></br>**Note:** `rejectOnNotFou
See https://github.com/prisma/docs/pull/5018/files#r1259701051

2023-07-11 13:04 UTC, janpio reviewed
See comments

2023-07-11 16:37 UTC, Jolg42 approved these changes

2023-07-11 16:55 UTC, merged