Metrics-output-improvements
prisma/prisma2-docs pull request #5299
Opened 2023-09-11 11:07 UTC by ruheni

Wrap metrics output in a CodeWithResult component

2023-09-11 16:50 UTC, janpio requested changes
See Slack comment

2023-09-12 16:17 UTC, janpio commented on content/200-concepts/100-components/02-prisma-client/240-metrics.mdx
> +      "key": "query_total_operations",
This does not look like a Prisma metric.

2023-09-12 16:17 UTC, janpio commented on content/200-concepts/100-components/02-prisma-client/240-metrics.mdx
> +      "labels": { "server": "us_server1", "app_version": "one" },
labels should be empty here or not even present.

2023-09-12 17:08 UTC, janpio approved these changes

2023-09-13 07:12 UTC, ruheni commented on content/200-concepts/100-components/02-prisma-client/240-metrics.mdx
> +      "labels": { "server": "us_server1", "app_version": "one" },
```suggestion
      "labels": { },
```

2023-09-13 07:13 UTC, ruheni commented on content/200-concepts/100-components/02-prisma-client/240-metrics.mdx
> +    },
```suggestion
    {
      "key": "prisma_client_queries_total",
      "labels": {},
      "value": 2,
      "description": "Total number of Prisma Client queries executed"
    },
    {
      "key": "prisma_datasource_queries_total",
      "labels": {},
      "value": 5,
      "description": "Total number of Datasource Queries executed"
    },
    {
      "key": "prisma_pool_connections_open",
      "labels": {},
      "value": 1,
      "description": "Number of currently open Pool Connections"
    }
```

2023-09-13 09:02 UTC, merged