fix: table dimensions + alignments
prisma/prisma2-docs pull request #5319
Opened 2023-09-15 13:29 UTC by carlagn

Fixes [#505](https://github.com/prisma/website/issues/505)

Please refer to this comment: https://github.com/prisma/website/issues/505#issuecomment-1700941316

2023-09-18 09:23 UTC, meletj requested changes
- [ ] Microsoft SQL server column under 'Constraints' table should also be center aligned

I checked the comment on the other PR, but I couldn't find the reasoning behind changing the width back to standard. Any reason we cannot leave it as 'wide: true'?

2023-09-18 10:52 UTC, carlagn commented
> * [ ]  Microsoft SQL server column under 'Constraints' table should also be center aligned
> 
> I checked the comment on the other PR, but I couldn't find the reasoning behind changing the width back to standard. Any reason we cannot leave it as 'wide: true'?

@Techboidesign left a comment [here](https://github.com/prisma/website/issues/505#issuecomment-1719330375) on that for you. Asking the same actually: wether or not we keep the `wide` frontmatter.

2023-09-18 13:04 UTC, meletj commented
I'd say we keep it to 'wide: true' for this page - this is a one-off / special case.

2023-09-19 10:03 UTC, meletj approved these changes

2023-09-19 15:05 UTC, merged