Update 03-generators.mdx
prisma/prisma2-docs pull request #5742
Opened 2024-03-21 23:30 UTC by m1212e

I made [prismabox](https://github.com/m1212e/prismabox), a generator to generate typebox schemes from the prisma scheme. Found it very useful when used with elysia and since there is no typebox tool listed yet, I think it would help people in the same situation

2024-03-27 17:26 UTC, jharrell commented on content/200-orm/100-prisma-schema/10-overview/03-generators.mdx
> +- [`prismabox`](https://github.com/m1212e/prismabox): Generates versatile [typebox](https://github.com/sinclairzx81/typebox) schemes from your Prisma models.
```suggestion
- [`prismabox`](https://github.com/m1212e/prismabox): Generates versatile [typebox](https://github.com/sinclairzx81/typebox) schema from your Prisma models.
```

2024-03-27 17:54 UTC, jharrell commented
Hi there! Thank you for your contribution (both to our docs and to our community) 🙂 

I see that your repo was forked from another project. Is that project still maintained? Generally speaking, we'd appreciate it if custom generators matched out suggested naming scheme of `prisma-generator-<custom name>`. 

To summarize:
- it's unclear to me if https://github.com/adeyahya/prisma-typebox-generator is still maintained. If it's not, would it be possible for you to take over the maintenance of that project? If it is maintained, could you pass your updates to the upstream project and we can list that?
- we prefer generators to have the naming scheme of `prisma-generator-<name>`. In this case it would be `prisma-generator-typebox`. (I understand that is pretty confusing with `prisma-typebox-generator` still existing, so if you're unable to get in contact with the maintainers of that project, nevermind this)

2024-03-27 17:55 UTC, jharrell requested changes
blocked pending discussion around related project.

2024-03-27 20:14 UTC, m1212e commented
I see. I opened a few issues asking for features/bugfixes but never got a response, so I think it's not maintained anymore.

I really like "prismabox" :D Fits so good. But if thats your policy I see why a rename would make sense.

2024-06-10 15:16 UTC, jharrell approved these changes

2024-06-10 15:18 UTC, merged