add note under datetime in schema reference
prisma/prisma2-docs pull request #5801
Opened 2024-04-03 16:13 UTC by grpatel

Fixes #5799

2024-04-04 08:25 UTC, nikolasburk requested changes, later dismissed
looks great, thanks Grishma! just want small change please to write "Prisma ORM" instead of "we"

2024-04-04 08:25 UTC, nikolasburk commented on content/200-orm/050-overview/500-databases/400-mysql.mdx
> +| `DateTime` | `DATETIME(3)`    | Currently, we do not support zero dates (`0000-00-00`, `00:00:00`) in MySQL |
Let's write "Prisma ORM does not support" instead of "we"

2024-04-04 10:16 UTC, janpio commented
(Also see my comments in Slack, please)

2024-04-04 19:57 UTC, grpatel commented
> (Also see my comments in Slack, please)

added mysql docs link and zero datetime (`0000-00-00 00:00:00`) here: [7d4a7cb](https://github.com/prisma/docs/pull/5801/commits/7d4a7cb27f17d285efc77c067f6ec95be93c09d7)

created [task](https://www.notion.so/prismaio/Docs-Expand-on-MySQL-datetime-not-supported-e51fef9d77b04ad9a623a8001c35eb87?pvs=4) to expand on this content in the future

2024-05-02 00:09 UTC, jharrell approved these changes

2024-05-02 00:12 UTC, merged