Update descriptions for `UserWhereUniqueInput` in reference
prisma/prisma2-docs pull request #5962
Opened 2024-04-30 13:26 UTC by nikolasburk

2024-04-30 13:31 UTC, jharrell approved these changes, later dismissed

2024-04-30 13:37 UTC, janpio commented on content/200-orm/500-reference/050-prisma-client-reference.mdx
> +| `where`                         | `UserWhereUniqueInput`   | **Yes**  | Wraps all fields of a model so that a record can be selected ([learn more](#filter-on-non-unique-fields-with-userwhereuniquei
Actual change is here

2024-04-30 14:03 UTC, janpio requested changes
undesired unrelated changes

2024-11-08 15:47 UTC, jharrell approved these changes

2024-11-08 15:47 UTC, merged