Update 425-nextjs-prisma-client-monorepo.mdx /  Altered doc to support next.config.mjs (newer versions of next use this)
prisma/prisma2-docs pull request #6044
Opened 2024-05-28 13:13 UTC by chris-cotech

Alter the bottom of the documentation to include code snippet helper for `next.config.mjs` (newer versions of next use this instead of next.config.js).

I have tested and confirmed in my Vercel deployment that the amendment to the documentation I am proposing works.

2024-06-07 15:21 UTC, millsp approved these changes

2024-06-10 14:30 UTC, jharrell commented on content/200-orm/800-more/600-help-and-troubleshooting/100-help-articles/425-nextjs-prisma-client-monorepo.mdx
> +```js copy
````suggestion
Alternatively, if you are using `next.config.mjs`, you may alter the file as such:

```js file=next.config.mjs
````

2024-06-10 14:30 UTC, jharrell requested changes
Thanks for the PR! One change needed then this is good to merge 😊

2024-06-11 18:00 UTC, chris-cotech commented
No worries, applied the suggested change and all set.

2024-06-11 18:41 UTC, jharrell approved these changes

2024-06-11 20:02 UTC, merged