add missing allow-no-models docs and new no-hints argument
prisma/prisma2-docs pull request #6046
Opened 2024-05-28 20:44 UTC by nickcarnival

## Reason:
The `--allow-no-models` argument is missing from the docs.
The `--no-hints` argument should be added soon and would be missing from the docs🤞 

## Changes
I added these arguments to the `generate` command arguments table `200-prisma-cli-reference.mdx`

These PRs are related to these changes hence the Draft status:

- This adds the `generate` arguments to the completion spec [PR](https://github.com/withfig/autocomplete/pull/2345/files)
- This adds the `--no-hints` argument to the `generate` cli command: [prisma cli PR](https://github.com/prisma/prisma/pull/24274)

2024-06-11 20:13 UTC, jharrell requested changes
One minor change. Planning to merge this alongside the release of 5.16.0.

2024-06-11 20:13 UTC, jharrell commented on content/200-orm/500-reference/200-prisma-cli-reference.mdx
> +| `--no-hints`          | No       | The `generate` command will generate Prisma Client without the 'Start using Prisma Client' and Accelerate messages.
```suggestion
| `--no-hints`          | No       | The `generate` command will generate Prisma Client without usage hints being printed to the terminal. Available in Prisma ORM 5.16.0 and later.                                                                                                                 |
```

2024-06-12 14:41 UTC, nickcarnival commented on content/200-orm/500-reference/200-prisma-cli-reference.mdx
> +| `--no-hints`          | No       | The `generate` command will generate Prisma Client without the 'Start using Prisma Client' and Accelerate messages.
Thanks!

2024-06-17 15:16 UTC, jharrell approved these changes

2024-06-25 14:27 UTC, merged