Added authSource configuration to the "Start from Scratch" section for MongoDB.
prisma/prisma2-docs pull request #6231
Opened 2024-08-31 06:55 UTC by yash-278

### Update `100-connect-your-database-typescript-mongodb.mdx`

Added `authSource` configuration to the "Start from Scratch" section for MongoDB.

**Reason for this update:** The `authSource` option was not mentioned in the "Start from Scratch" section, which could be particularly crucial for new developers. Including this tip here can help address potential authentication issues for those setting up their environment from the beginning, whereas experienced developers might already be familiar with such details.

Reference: [Issue](https://github.com/prisma/prisma/discussions/9994#discussioncomment-1562283)

2024-09-02 11:45 UTC, yash-278 commented
@Dev-Connections Kindly check if this is a valid change.

2024-09-02 18:50 UTC, yash-278 commented
Not sure what the convention is to bring attention from Dev team for PR reviews, so hence I'm tagging 😅

 @jharrell

2024-09-03 16:51 UTC, jharrell requested changes
Thank you for your contribution! Made one suggestion.

2024-09-03 16:51 UTC, jharrell commented on content/100-getting-started/02-setup-prisma/100-start-from-scratch/120-mongodb/100-connect-your-database-typescript-mongodb.mdx
> +> If you see the following error: `Error in connector: SCRAM failure: Authentication failed.`, you can specify the source database for the authentication by [adding](https://github.com/prisma/prisma/
```suggestion
> If you see the following error: `Error in connector: SCRAM failure: Authentication failed.`, you can specify the source database for the authentication by adding `?authSource=admin` to the end of the connection string. See [this GitHub discussion](https://github.com/prisma/prisma/discussions/9994#discussioncomment-1562283) for additional details.
```

2024-09-04 12:31 UTC, yash-278 commented on content/100-getting-started/02-setup-prisma/100-start-from-scratch/120-mongodb/100-connect-your-database-typescript-mongodb.mdx
> +> If you see the following error: `Error in connector: SCRAM failure: Authentication failed.`, you can specify the source database for the authentication by [adding](https://github.com/prisma/prisma/
Added, Thanks!

2024-09-04 12:56 UTC, jharrell approved these changes

2024-09-04 12:58 UTC, merged