Raw SQL doc update
prisma/prisma2-docs pull request #728
Opened 2020-08-03 07:12 UTC by mhwelander

2020-08-03 09:50 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +The same method is implemented as a tagged template, which makes it easier to use [variables](#using-variables-and-helpers). The following example includes an `${email}` variable:
tagged template might deserve an external link to some docs that explain what it is

2020-08-03 09:50 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +You also [type the results of `queryRaw`](#typing-queryraw-results).
```suggestion
You can also [type the results of `queryRaw`](#typing-queryraw-results).
```

2020-08-03 09:51 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +> **Note**: If you do not provide a type, `queryRaw` defaults to `any`.
is here inside the example the right place for this comment?

2020-08-03 09:52 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +> **Note**: The Prisma Client query engine standardises the return type for all databases.
```suggestion
> **Note**: The Prisma Client query engine standardises the return type for all databases. Using the raw queries does not.
```

2020-08-03 09:52 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +The same method is implemented as a tagged template, which makes it easier to use [variables](#using-variables-and-helpers):
link for "tagged template" as above

2020-08-03 09:54 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +* Tagged templates are database-agnostic - you do not need to remember if variables should be written as is `$1` (PostgreSQL) or `?` (MySQL)
not sure, but maybe:
```suggestion
* Tagged templates are database-agnostic - you do not need to remember if variables should be written as `$1` (PostgreSQL) or `?` (MySQL)
```

2020-08-03 09:54 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +> **Note**: You cannot pass in table or column names as tagged template variables.
waht does that mean really? what is impossible because of that?

2020-08-03 09:55 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +The same query written using tagged templates is easier to read and works with all database providers:
"tagged templates" could link to that section here, above

2020-08-03 15:43 UTC, mhwelander commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +* Tagged templates are database-agnostic - you do not need to remember if variables should be written as is `$1` (PostgreSQL) or `?` (MySQL)
```suggestion
* Tagged templates are database-agnostic - you do not need to remember if variables should be written as `$1` (PostgreSQL) or `?` (MySQL)
```

2020-08-03 15:43 UTC, mhwelander commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +* Tagged templates are database-agnostic - you do not need to remember if variables should be written as is `$1` (PostgreSQL) or `?` (MySQL)
```suggestion
* Tagged templates are database-agnostic - you do not need to remember if variables should be written as `$1` (PostgreSQL) or `?` (MySQL)
```

2020-08-03 16:39 UTC, janpio commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +> **Note**: `executeRaw` does not support [multiple queries in a single string]() (for example, `ALTER TABLE` and `CREATE TABLE` together).
missing link target

2020-08-04 09:26 UTC, thebiglabasky requested changes
I mostly focused my review on the SQL injection piece. I think it looks great!

2020-08-04 09:26 UTC, thebiglabasky commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +The following example concatanates `query`and `inputString`. Prisma Client ❌ **cannot** escape `inputString` in this example, which makes it vulnerable to SQL injection:
concatanates > concatenates

2020-08-04 09:26 UTC, thebiglabasky commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +### Warning: Template literals
Do we capitalize `Template`? I thought we'd do `Warning: template literals`

2020-08-04 09:26 UTC, thebiglabasky commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +* Prisma Client escapes all variables when you use tagged templates (``` queryRaw`` ``` or ``` executeRaw`` ``` ) or parameterized queries (`queryRaw(query, variables)` or `executeRaw(query, variable
sends all queries > performs all queries ?

2020-08-04 09:26 UTC, thebiglabasky commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +If you cannot use tagged templates or parameterized queries (for example, you need to pass in table or column names as variables), be aware that your code may be vulnerable to SQL injection.
`to SQL injection**s**` or `to an SQL injection`

2020-08-04 09:26 UTC, thebiglabasky commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +The following example concatanates `query`and `inputString`. Prisma Client ❌ **cannot** escape `inputString` in this example, which makes it vulnerable to SQL injection:
`to SQL injection` > `to SQL injections` (but maybe there's something I'm missing?)

2020-08-04 09:26 UTC, thebiglabasky commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +The following example uses a template literal inside `queryRaw()`and returns all users where `name` equals `${inputString}`. Prisma Client ❌ **cannot** escape `inputString` in this example, which mak
Sames here with SQL injection. I now really wonder if I'm not expecting something wrong? I'd generally pluralize that or add `an` in front.

2020-08-04 09:26 UTC, thebiglabasky commented on content/03-reference/01-tools-and-interfaces/02-prisma-client/090-raw-database-access.mdx
> +const result = await prisma.queryRaw`SELECT * FROM User ${
Could be cool to comment the "generated" SQL maybe? That may look a bit cryptic to read only through code.

2020-08-04 12:58 UTC, merged